version: '3.8'

services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
